fix Projects section
cetav-ddw/cegea pull request #11
Opened 2019-10-21 16:36 UTC by LilMonRod

2019-10-22 03:16 UTC, jleiva requested changes

2019-10-22 03:16 UTC, jleiva commented on src/index.html
> +            <img src="./images/proyectos/mobile-conservacion-jardines.jpg" alt="fotografia de nuestros programa de conservación de jardines del parque">
mobile no puede ser el default, porque si un browser no soporta picture va a cargar la image "mobile"

2019-10-22 15:28 UTC, YethPenado commented on src/index.html
> +            <img src="./images/proyectos/mobile-reforestacion.jpg" alt="fotografia de uno de nuestros proyectos de Reforestación del parque">
Este alt no es muy descriptivo. Puede ser algo como "Fotografía de una de las zonas que han sido reforestadas dentro del Parque La Libertad".
Además, "fotografía" va tildado (esto en todos los alt).

2019-10-22 15:28 UTC, YethPenado commented on src/scss/components/_projects.scss
>      font-size: $h3-size;
En el breakpoint de sm, el tamaño de la letra es muy pequeño.

2019-10-23 16:20 UTC, jleiva requested changes

2019-10-23 16:20 UTC, jleiva commented on src/index.html
> +            <img src="./images/proyectos/laptop-jardin-botanico.jpg" alt="Fotografía de nuestros jardines">
el alt no necesita llevar la palabra fotografia, y si quieren poner alt, deber ser una descripcion que le aporte valor al usuario. Si la imagen es meramente decorativa, lo que significa que si no hay imagen no pasa nada, no se afecta el contenido, entonces el alt puede quedar vacio

2019-10-23 16:21 UTC, merged