Impact
cetav-ddw/cegea pull request #12
Opened 2019-10-24 15:05 UTC by YethPenado

2019-10-24 15:12 UTC, LilMonRod commented on src/about.html
> +      <li class="impact__item impact__item--teacher">
como sugerencia ese modifier "impact__item--teacher" sería más semántico si lo cambia por "impact__item--education"

2019-10-24 15:55 UTC, LilMonRod requested changes

2019-10-24 15:55 UTC, LilMonRod commented on src/scss/components/_impact.scss
> +  background-image: url(../images/impact/impact-1.jpg);
creo que sería bueno incluir una imagen de mejor calidad para los casos de retina

2019-10-24 15:55 UTC, LilMonRod commented on src/scss/components/_impact.scss
> +.impact__item__description {
Para evitar el desajuste con la alineacion de los iconos puede jugar con la altura de los p adaptandola a los diferentes mq

2019-10-24 15:55 UTC, LilMonRod commented on src/about.html
> +      <li class="impact__item impact__item--teacher">
como sugerencia ese modifier "impact__item--teacher" sería más semántico si lo cambia por "impact__item--education"

2019-10-25 04:06 UTC, jleiva requested changes

2019-10-25 04:06 UTC, jleiva commented on src/about.html
> +  <section id="our-impact" class="wrapper">
Ojo que esto no tiene header ni footer; donde usas el id our-impact?

Esto es toda la seccion de Acerca?

2019-10-25 04:06 UTC, jleiva commented on src/about.html
> +        <img src="images/icons/impact/impact-icon__1.png" alt="" class="impact__item__icon">
si son solo iconos, talvez la manera mas sencilla de incluirlos es usando background image, similar a lo que hizo Yeth en el footer

2019-10-25 21:08 UTC, YethPenado commented on src/about.html
> +  <section id="our-impact" class="wrapper">
- No puse eso todavía porque estaba esperando que estuvieran bien pulidos antes de incorporarlos.
- Hay un sub-menú en esta sección, por eso necesito ese id.
- No, evidentemente no. Faltan varias cosas más, pero vamos trabajando por componentes, ¿no?

2019-10-26 02:19 UTC, jleiva commented on src/about.html
> +  <section id="our-impact" class="wrapper">
pero porque no incluirle el header y footer?

2019-10-30 02:36 UTC, jleiva commented
@YethPenado podes verificar que tu branch esta al dia con develop, hay un conflicto en index.html

2019-11-07 03:17 UTC, merged