Logros
cetav-ddw/cegea pull request #13
Opened 2019-10-24 17:22 UTC by danielaaj12

aquí está la sección de nuestras insignias

2019-10-25 04:19 UTC, jleiva requested changes

2019-10-25 04:19 UTC, jleiva commented on src/index.html
> +    <h2 class="achievements__title">Nuestros
los estilos de este toque del titulo deberian de ser los mismos en las secciones donde las usan, y tener las mismas clases, estan repitiendo codigo

2019-10-25 04:19 UTC, jleiva commented on src/index.html
> +        <img class="achievements__image" src="./images/logros/crow.png" alt="En el parque se registran 133 aves.">
si los iconos los incluis usando background image, vas a tener mas control para posicionarlos, ademas, el alt no tiene relacion con el icono.

Si esos textos son tan importantes, talvez el texto deberia de estar ahi y no dividido a como lo tenes, porque a nivel de codigo, +300 y Aves Registradas no tienen relacion. Una manera de solucionarlo es tener el texto y hacer un reemplazo del texto con una imagen

2019-10-25 04:19 UTC, jleiva commented on src/scss/components/_achievements.scss
> +  border-bottom-left-radius: 45px * 2;
porque no solo usar 90px?

2019-10-28 05:11 UTC, YethPenado commented on src/index.html
> +      <span class="titles--font">Logros</span>
Ya habíamos dicho que la segunda palabra no es un sustantivo propio, por ende, tiene que ir en minúscula.

2019-10-28 05:11 UTC, YethPenado commented on src/index.html
>        <li class="achievements__item achievements__birds">
En la segunda clase, el modificador es "birds", por eso debería ir con doble guión -- en lugar de guión bajo.

2019-10-28 05:11 UTC, YethPenado commented on src/index.html
> +        <p class="achievements__description--green">Árboles reforestados</p>
Al p de la línea 189 le hace falta la clase "achievements__description" (sólo tiene la clase modificadora) por ende, no tiene el mismo estilo que los otros dos.

2019-10-28 05:11 UTC, YethPenado commented on src/scss/components/_achievements.scss
> +.achievements__description {
En pantallas grandes, hace falta un tamaño de letra más grande. Un size-font de 1.25rem queda bastante bien. Podés implementarlo a partir del breakpoint-lg

2019-10-28 05:11 UTC, YethPenado commented on src/scss/components/_achievements.scss
> +  font-size: 21px;
Estás usando pixeles para ese tamaño de fuente. Usamos rem. El equivalente a ese tamaño es 1.375rem

2019-10-28 16:53 UTC, LilMonRod commented on src/index.html
> +      <span class="titles--font">Logros</span>
La clase del h2 y span hay que cambiarla por una general

2019-10-28 16:54 UTC, LilMonRod commented on src/index.html
> +        <p class="achievements__description--green">Árboles reforestados</p>
los modificadores tienen doble guion bajo (__) en lugar de doble guion (--)
achievements__birds
achievements__trees
achievements__volunteers

2019-10-28 16:58 UTC, LilMonRod commented on src/index.html
> +        <p class="achievements__description--green">Árboles reforestados</p>
ejemplo:
achievements__item--trees

2019-11-01 19:10 UTC, YethPenado requested changes

2019-11-01 19:10 UTC, YethPenado commented on src/scss/components/_achievements.scss
> +  width: 200px;
Ese width de 200px es mucho en Mobile, se estira a tal punto que se "sale" de la pantalla.

2019-11-07 03:24 UTC, jleiva commented on src/scss/styles.scss
> +@import 'components/achievements';
esta dos veces el import

2019-11-07 03:24 UTC, jleiva requested changes

2019-11-07 03:24 UTC, jleiva commented on src/index.html
> +        <p class="achievements__descript--bird achievements__description">Más de 3000 aves registradas</p>
el texto deberia de ser "visible" solo para screen readers, Lilliam habia incluido una clase para eso.

2019-11-07 03:32 UTC, merged

2019-11-07 03:33 UTC, jleiva commented on src/index.html
> +        <p class="achievements__descript--bird achievements__description"><span class="sr-only">Más de 3000 aves registradas</span></p>
el texto deberia de ser "visible" para screen readers