About- navigation (secondary menu)
cetav-ddw/cegea pull request #16
Opened 2019-10-31 18:00 UTC by YethPenado

2019-11-07 03:47 UTC, jleiva requested changes

2019-11-07 03:47 UTC, jleiva commented on src/about.html
> +      <h1 class="brand">
en la secciones internas lo que tenemos como logo no deberia de ser un h1, el titulo de la pagina deberia ser el h1

2019-11-07 03:47 UTC, jleiva commented on src/scss/components/_about-nav.scss
> +  &:nth-child(4n) {
un espacio antes, y revisa la identacion, porfa

2019-11-07 03:47 UTC, jleiva commented on src/scss/components/_about-nav.scss
> +  @media (min-width: 515px) {
estos media queries a quien modifican? ademas, linea 42 y 48 tienen el mismo valor

2019-11-07 03:47 UTC, jleiva commented on src/scss/components/_about-nav.scss
> +.about-nav {
la version movil esta incompleta? porque no se ve bien

![image](https://user-images.githubusercontent.com/598867/68358751-0cc27900-00df-11ea-878c-c2e8d071e1c6.png)

2019-11-12 14:36 UTC, danielaaj12 commented on src/scss/components/_about-nav.scss
> +.about-nav {
lo que puedes hacer ahí es alinear nuestro impacto con nuestra historia y nuestro enfoque con cegea y quitar la línea que está demás

2019-11-12 14:43 UTC, danielaaj12 commented on src/scss/components/_about-nav.scss
> +  @media (min-width: 515px) {
si no me equivoco yeth está modificando al a que está dentro del li

2019-11-14 16:41 UTC, closed without merging