added images and styles for focus section
cetav-ddw/cegea pull request #17
Opened 2019-10-31 18:01 UTC by LilMonRod

Se agregó la sección de focus en about.html

2019-11-01 18:33 UTC, YethPenado requested changes

2019-11-01 18:33 UTC, YethPenado commented on src/about.html
> +  </section>
Esto es lo que yo trabajé en el pull request de Impact, tenés que quitarlo.

2019-11-01 18:33 UTC, YethPenado commented on src/about.html
> +    </ul>
"Gallery" no es tan semántico, pueden existir otras galerías en el sitio y ahí va chocar. Considero que es mejor dejarlo como "focus" tal cosa.

2019-11-01 18:33 UTC, YethPenado commented on src/scss/components/_focus.scss
> +  transition: 0.3s ease-in-out;
Esto no está ordenado alfabéticamente.

2019-11-01 18:33 UTC, YethPenado commented on src/scss/styles.scss
> +@import 'components/focus';
@jleiva tengo una duda respecto al orden de este documento. "Focus" ya le pertenece a otra sección del sitio, por eso Lilliam lo está poniendo un poco aparte. Sin embargo, desde mi punto de vista, se debe respetar la cascada, y el Footer siempre va a estar de último en todo. ¿Separamos los componentes por secciones o respetamos la cascada?

2019-11-01 18:33 UTC, YethPenado commented on src/scss/util/_layout.scss
> +  margin-bottom: 35px;
Bottom va antes que Top.

2019-11-04 15:30 UTC, LilMonRod commented on src/about.html
> +    </ul>
es **focus-gallery** no solo gallery

2019-11-04 15:31 UTC, LilMonRod commented on src/scss/styles.scss
> +@import 'components/focus';
cierto, yo también tengo esa duda.

2019-11-04 15:33 UTC, LilMonRod commented on src/about.html
> +  </section>
ya lo quito

2019-11-05 17:47 UTC, YethPenado commented on src/about.html
> +    </ul>
Ya vi, perdón por nacer :c

2019-11-07 04:11 UTC, jleiva requested changes

2019-11-07 04:11 UTC, jleiva commented on src/scss/components/_focus.scss
> +.focus__description {
con todo mi CNV, pero focus es una pesima clase, focus es un estado y un pseudo-class, ademas, estas casi  amarrando el nombre de la clase a lo que dice el texto, impiendo que se pueda reusar en otro lado

2019-11-07 04:11 UTC, jleiva commented on src/scss/styles.scss
> +@import 'components/focus';
lo que les dije por slack.

1. Los imports se pueden ordenar de manera alfabetica
2. Van primeros variables, mixins, functions, etc
3. Despues de los imports del punto #2, pueden ir patterns y despues components
4. El orden de los imports, dejando por fuera el punto #2, no deberia de afectar la cascada, si afecta es porque hay no esta bien, los componentes deberian de ser independientes y no afectar  nada "fuera" de ellos

2019-11-07 04:11 UTC, jleiva commented on src/about.html
> +      <h1 class="brand">
a Yeth le deje el mismo comentario, el logo no deberia de ser el h1 en las secciones internas, el titulo de la pagina es el h1

2019-11-07 04:13 UTC, jleiva requested changes

2019-11-07 04:13 UTC, jleiva commented on src/about.html
> +    <p class="focus__description">
el ancho de los textos no puede ser de 1400px, es demasiado, complica la lectura

![image](https://user-images.githubusercontent.com/598867/68359727-99226b00-00e2-11ea-815c-daeaecd47d74.png)

2019-11-07 15:14 UTC, LilMonRod commented on src/scss/components/_focus.scss
> +.focus__description {
La sección se llama Nuestro enfoque, qué nombre de clase recomienda para ese componente? en realidad sería para la galleria y para el contenedor porque los títulos de sección ya tienen una clase general y la mayoría de los textos descriptivos va a tener estilos iguales asi que se está pasando a una clase general también.

2019-11-12 14:38 UTC, danielaaj12 commented on src/about.html
> +    <p class="focus__description">
Lil la idea es alinearlo al borde de las imágenes

2019-11-14 17:09 UTC, jleiva requested changes

2019-11-14 17:09 UTC, jleiva commented on src/scss/components/_odd-gallery.scss
> +  @media (min-width: $breakpoint-sm) {
si estos media query afectan odd-gallery__item, deben ir antes de hover

2019-11-14 17:09 UTC, jleiva commented on src/about.html
> +      <h1 class="brand">
y esto?

2019-11-14 17:22 UTC, LilMonRod commented on src/about.html
> +      <h1 class="brand">
right... ya lo cambio

2019-11-14 18:03 UTC, LilMonRod commented on src/about.html
> +    <p class="focus__description">
ya se corrigió

2019-11-14 18:03 UTC, LilMonRod commented on src/scss/components/_odd-gallery.scss
> +  @media (min-width: $breakpoint-sm) {
corregido

2019-11-14 18:41 UTC, merged