Sección - Acerca del CEGEA
cetav-ddw/cegea pull request #20
Opened 2019-11-11 00:25 UTC by YethPenado

2019-11-14 15:02 UTC, jleiva requested changes

2019-11-14 15:02 UTC, jleiva commented on src/about.html
> +    <p class="descrip__text descrip__text--spacing">Actualmente nos encontramos trabajando en:</p>
estas usando un modificador pero no hay clase base

2019-11-14 15:02 UTC, jleiva commented on src/about.html
> +      <source media="(min-width: 768px)" srcset="./images/cegea/cegea__titular--2x.jpg">
ya se lo habia dicho a Liliam en otro momento, 2x se usa en el nombre de las imagenes cuando se tienen cosas para retina, ademas, no usen ese formato tan raro para nombrar archivos de imagenes

2019-11-14 15:02 UTC, jleiva commented on src/scss/util/_layout.scss
> +.descrip__text {
si esto es el partial de layout, aqui no deben ir cosas de textos o titulos

2019-11-14 15:02 UTC, jleiva commented on src/scss/components/_cegea.scss
> +    background-image: url(../../images/cegea/cegea__offer-meetup-2x.jpg);
mismo comentario, 2x hace referencia a retina, aqui solo cambiar la imagen por beakpoint y no uses ese formato de nombrar imagenes, con guiones es mas que suficiente

2019-11-14 19:03 UTC, LilMonRod commented on src/scss/components/_cegea.scss
> +    background-image: url(../../images/cegea/cegea__offer-meetup-2x.jpg);
BEM style

2019-11-14 19:03 UTC, LilMonRod commented on src/scss/util/_layout.scss
> +.descrip__text {
esto se corrige con actualizar develop

2019-11-15 17:20 UTC, YethPenado commented on src/about.html
> +    <p class="descrip__text descrip__text--spacing">Actualmente nos encontramos trabajando en:</p>
"descrip__text" es la clase base, es una clase general que estamos usando para los textos.

2019-11-16 17:01 UTC, merged