Introducción a la sección de Gestión Ambiental
cetav-ddw/cegea pull request #21
Opened 2019-11-14 18:07 UTC by YethPenado

Iniciando la sección de Gestión Ambiental

2019-11-14 18:49 UTC, jleiva requested changes

2019-11-14 18:49 UTC, jleiva commented on src/environmental-management.html
> +        <span class="locations__icon">
un p no puede ir dentro de un span, el span es un elemento de linea y el p es de bloque

2019-11-14 18:49 UTC, jleiva commented on src/scss/components/_env-management.scss
> +    max-width: 90%;
linea 8 tiene el mismo valor

2019-11-14 18:49 UTC, jleiva commented on src/scss/components/_env-management.scss
> +    font-size: 1.375rem;
porque no estas usando las variables para tamaños de fuentes?

2019-11-14 18:49 UTC, jleiva commented on src/scss/patterns/_text.scss
> +.titles--font {
pueden usar una clase mas descriptiva, porfa, --font no comunica nada

2019-11-15 19:32 UTC, YethPenado commented on src/scss/patterns/_text.scss
> +.titles--font {
Quedó como titles--bold

2019-11-15 21:06 UTC, YethPenado commented on src/scss/components/_env-management.scss
> +    font-size: 1.375rem;
Hemos notado que, en efecto, estamos reutilizando tamaños de fuentes en otros lados sin usar variables y quedamos en corregir esto el lunes.

2019-11-16 17:06 UTC, merged