Actions
cetav-ddw/cegea pull request #25
Opened 2019-11-27 23:05 UTC by JgeovanniAm

2019-11-30 23:40 UTC, YethPenado requested changes

2019-11-30 23:40 UTC, YethPenado commented on src/environmental-management.html
> +    <p class="descrip__text">Este programa es el núcleo de trabajo del Eje Ambiental. A través de una gestión asociada,
Revisar la indentación de estos párrafos.

2019-11-30 23:40 UTC, YethPenado commented on src/environmental-management.html
> +    <p>Dentro de las acciones principales de la gestión ambiental se encuentran:</p>
A ese texto le falta la clase "descrip__text"

2019-11-30 23:40 UTC, YethPenado commented on src/environmental-management.html
> +          <h2>Reforestación</h3>
No creo que sea semánticamente correcto que estos sean `<h2>`. Bien pueden ser `<p>` o un rango menor de `<h>`

2019-11-30 23:40 UTC, YethPenado commented on src/scss/patterns/_card.scss
> +.main-actions__cards {
Comentarios generales a nivel visual:

- Los tamaños de las cards para los breakpoints de 768 para abajo, están muy grandes.
- Aunque los 'títulos' están centrados, _realmente no se ven centrados_ . Esto pasa porque están centrados a nivel del padre, pero ya que tienen ese círculo encima (que abarca parte del espacio superior del `<div>`) quita la visión de que están centrados y parece más bien que dichos títulos están tirados hacia arriba. Creo que eso puede solucionarse con un `margin-top` de tantos pixeles.
- Los íconos se ven un tanto bruscos con ese tamaño. Hay que bajarles un poco.
- En breakpoints superiores a 1024 las cajas se ven muy separadas entre sí (a nivel horizontal).

2019-11-30 23:40 UTC, YethPenado commented on src/scss/components/_actions.scss
> +  background: $orange-dark;
En el diseño, los círculos tienen un color más oscuro que la caja, ambos elementos no comparten el mismo color. Voy a ponerte acá los colores correctos:

CÍRCULOS:
- Café: 82462C;
- Verde: 5F9750;
- Amarillo: DCAE12;
- Naranja: EB751F;

CAJAS:
- Café: A06044;
- Verde: 75A667;
- Amarillo: E9C13A;
- Naranja: EF8538;

Si alguno de estos colores no está en el archivo de variables, agregalo ahí porfa. Creo que los cafés no están, entonces hay que pasarlos a variable.

2019-12-05 01:19 UTC, jleiva requested changes

2019-12-05 01:19 UTC, jleiva commented on src/about.html
> +        <img src="./" alt="">
ojo el scr esta vacio

2019-12-06 01:24 UTC, merged