Navigation component
cetav-ddw/cegea pull request #3
Opened 2019-09-19 17:15 UTC by LilMonRod

2019-09-19 22:31 UTC, YethPenado commented on sass/navigation/_navigation.scss
> +  background-color: $yelow;
*Yellow

2019-09-19 22:35 UTC, YethPenado commented on sass/navigation/_navigation.scss
> +  }
Estamos usando Flexbox, no grids.

2019-09-19 23:05 UTC, danielaaj12 commented on index.html
> -                    <a class="main-nav__link" href="#">¿Quiénes somos?</a>
En vez de ¿quienes somo? es **"Acerca de nosotros"**

2019-09-19 23:08 UTC, YethPenado commented on css/main.css
> +  font-family: "Palanquin Dark", Arial, Verdana, sans-serif; }
font-family va primero

2019-09-19 23:09 UTC, danielaaj12 commented on index.html
> +          <img id="menuImg-js" class="btn-menu__img" src="images/icons/menu/menu.svg" alt="menu">
contextualizar mejor el alt del menú

2019-09-19 23:09 UTC, YethPenado commented on index.html
> +          <img id="menuImg-js" class="btn-menu__img" src="images/icons/menu/menu.svg" alt="menu">
ese alt puede ser más descriptivo, como "menú principal o navegación principal"

2019-09-19 23:24 UTC, jleiva requested changes

2019-09-19 23:24 UTC, jleiva commented on css/main.css
> +@import url("https://fonts.googleapis.com/css?family=Palanquin+Dark|Quicksand&display=swap");
no hay que incluir en los pull request el CSS compilado

2019-09-19 23:24 UTC, jleiva commented on index.html
> +    <h1 class="title">Dimensión ambiental</h1>
title como clase, no no

2019-09-19 23:24 UTC, jleiva commented on index.html
> +        <button id="btnMenu-js" class="btn-menu">
ponele el atributo type button, porfa

los IDs siguen la misma reglas que las clases, las palabras se separan con guion. Para las clases que usen js- en el nombre, que sea un prefijo, los IDs no necesitan llevar -js o js- 

Aplica para todo el documento donde estes usando lo mismo

2019-09-19 23:24 UTC, jleiva commented on index.html
> +  <main class="main-info">
hay un role main

2019-09-19 23:24 UTC, jleiva commented on index.html
> +      <h2 class="act__title">Próximas actividades</h2>
No se si esto es parte de tu cambio, pero seria mejor usar algo relacionado con agenda, calendar o similar, act no dice nada

2019-09-19 23:24 UTC, jleiva commented on js/menu.js
> +(function () {
hay que incluir eslint

2019-09-19 23:24 UTC, jleiva commented on js/menu.js
> +  function closeMenu() {
nueva linea entre funciones

2019-09-19 23:24 UTC, jleiva commented on js/menu.js
> +  const mq = window.matchMedia('(min-width: 768px)');
nombres de variables mas descriptivas, porfa, especificamente esto de mq

2019-09-19 23:24 UTC, jleiva commented on sass/_header.scss
> +body {
partial solo debe tener reglas relacionadas con el componente, body no tiene nada que ver con header

2019-09-19 23:24 UTC, jleiva commented on sass/_header.scss
> +  display: grid;
no estamos usando grid

2019-09-19 23:24 UTC, jleiva commented on sass/_header.scss
> +  padding: 3rem 1rem 2rem 1rem;
este padding se puede cambiar a 3rem 1rem 2rem

2019-09-19 23:24 UTC, jleiva commented on sass/_helpers.scss
> +.none {
una clase mas descriptiva, porfa

2019-09-19 23:24 UTC, jleiva commented on sass/main.scss
> +
eliminar las lineas entre imports

2019-09-19 23:24 UTC, jleiva commented on sass/main.scss
> +@import './navigation/navigation';
cual es el fin de tener un folder para navigation?

2019-09-19 23:24 UTC, jleiva commented on sass/navigation/_navigation.scss
> +.main-nav__cont {
ordenar los selectores alfabeticamente

2019-09-19 23:24 UTC, jleiva commented on js/menu.js
> +    if (mediaQuery.matches) {
para ocultar o mostrar el boton no se ocupa javascript, eso se puede manejar con CSS

2019-09-19 23:24 UTC, jleiva commented on js/menu.js
> +    imgMenu.removeAttribute('src');
el cambiar la imagen se puede manejar con CSS, y con javascript solo poner o quitar una clase cuando se le dio click al boton

2019-09-19 23:25 UTC, jleiva commented on index.html
> +          <img id="menuImg-js" class="btn-menu__img" src="images/icons/menu/menu.svg" alt="menu">
yo no usaria una imagen aqui, sino solo un buton con texto, y usar CSS para poner o quitar el svg que se quiere, como background image

2019-09-20 20:05 UTC, jleiva requested changes

2019-09-20 20:05 UTC, jleiva commented on js/menu.js
> +    console.log('si hizo click')
remove el console log

2019-09-20 20:05 UTC, jleiva commented on js/menu.js
> +    menuContainer.classList.add('hide');
Maneja una sola clase, la clase se va a llamar is-open, cuando se abre se pone esa clase, cuando se cierra se la quitas, es un toggle de la clase, ya con eso te quitas ese variable global de isClosedMenu.

En el CSS, si el elemento no tiene is-open, esta como display none, y le pones display block cuando tenga la clase

2019-09-20 20:05 UTC, jleiva commented on js/menu.js
> +  const btnMenu = document.getElementById('btn-menu');
js-btn-menu y js-cont-menu

2019-09-20 20:05 UTC, jleiva commented on sass/_helpers.scss
> +.hide {
con los cambios en el JS que te indique antes, estas clases se van

2019-09-20 20:05 UTC, jleiva commented on sass/_navigation.scss
> +  @media (min-width: $breakpoint-md) {
una linea nueva entre el bloque de reglas y lo anidado

2019-09-20 20:05 UTC, jleiva commented on sass/_navigation.scss
> +    padding: 1.2rem 1rem 0rem;
cuando el valor es 0, no hace falta la unidad

2019-09-20 20:05 UTC, jleiva commented on sass/_navigation.scss
> +  color: white;
$white

2019-09-20 20:05 UTC, jleiva commented on sass/_navigation.scss
> +.responsive {
esto se maneja con la clase de is-open, ojo el comentario en el archivo de JS

2019-09-20 20:05 UTC, jleiva commented on index.html
> +      <a class="agenda__acts-link" href="#">Más actividades</a>
agenda__link

2019-09-20 20:05 UTC, jleiva commented on sass/_helpers.scss
> +body {
body no debe estar en este partial, hace un partial nuevo, que se llame _base.scss, ahi van los estilos de body, html, o cualquier cosa que no caiga en componentes o patrones

2019-09-20 20:05 UTC, jleiva commented on sass/_navigation.scss
> +  margin: 1.5rem;
como estan calculando las medidas de los rem para padding y margin?

2019-09-23 17:59 UTC, merged