Sección Footer finalizada
cetav-ddw/cegea pull request #5
Opened 2019-09-26 20:42 UTC by YethPenado

2019-09-27 22:26 UTC, jleiva requested changes

2019-09-27 22:26 UTC, jleiva commented on src/scss/components/_footer.scss
> +    justify-content: space-between;
la misma declaracion esta en linea 6

2019-09-27 22:26 UTC, jleiva commented on src/scss/components/_footer.scss
> +.contact__title, .social__title {
un selector por linea. Si los dos titlos tienen las mismas reglas, podes usar un selector comun, asi no tenes que agrupar

2019-09-27 22:26 UTC, jleiva commented on src/scss/components/_footer.scss
> +  @media (min-width: 960px) {
una linea nueva antes de los media queries

2019-09-27 22:26 UTC, jleiva commented on src/scss/components/_footer.scss
> +footer {
footer no es un componente, footer esta compuesto de componentes, en este caso no es gran desplome porque footer no tiene gran cosa, pero como regla, es preferible que cada partial de Sass solo tengan reglas de un mismo componente, y si ya tiene mas de 50 lineas, hay que revisar si es que estas incluyendo cosas que deberian de ir en otro partial

2019-09-27 22:26 UTC, jleiva commented on src/scss/_base.scss
> +* {
seria mejor incluir normalize o algo similar

2019-09-27 22:26 UTC, jleiva commented on src/index.html
> +          <span class="contact__icon">
o el anchor dentro del p, o dentro del span, pero no un p dentro de un span, en escencial, un elemento inline no deberia de contener elementos de bloque

2019-09-27 22:27 UTC, LilMonRod commented on src/index.html
> +  <footer>
agregale role="contentinfo"

2019-09-27 22:44 UTC, LilMonRod requested changes

2019-09-27 22:44 UTC, LilMonRod commented on src/index.html
> +          <span class="social__icon"></span>
los iconos estan en span? no deberian ser img?

2019-09-27 22:44 UTC, LilMonRod commented on src/scss/components/_footer.scss
> +  @media (min-width: 720px) {
falta espacio anted del @media

2019-09-27 22:44 UTC, LilMonRod commented on src/index.html
> +  <footer>
agregale role="contentinfo"

2019-09-27 22:44 UTC, LilMonRod commented on src/scss/_variables.scss
>  $breakpoint-lg: 1024px;
corrija los breakponits
estos fueron los que se acordaron el viernes:
$breakpoint-xs: 320px;
$breakpoint-sm: 500px;
$breakpoint-md: 768px;
$breakpoint-lg: 1024px;
$breakpoint-xl: 1440px;

2019-09-28 04:28 UTC, danielaaj12 commented on src/index.html
> +          <span class="social__icon"></span>
creo que es mejor imagen para ponerle un alt

2019-09-28 04:28 UTC, danielaaj12 commented on src/scss/_variables.scss
>  $breakpoint-lg: 1024px;
igual los breakpoints recuerden que empiezan a partir del 768px (mobile first)

2019-10-02 16:24 UTC, merged