Calendario
cetav-ddw/cegea pull request #6
Opened 2019-09-28 19:07 UTC by danielaaj12

2019-10-02 17:03 UTC, YethPenado commented on src/scss/_base.scss
> +}
Es mejor utilizar un Normalize

2019-10-02 17:03 UTC, YethPenado commented on src/scss/_base.scss
> +p,span {
Si el <body> ya tiene especificado que la fuente a utilizar es $font-default, no es necesario repetir la instrucción en otros selectores

2019-10-02 17:03 UTC, YethPenado commented on src/index.html
>      </section>
Esto está repetido.

2019-10-02 17:03 UTC, YethPenado commented on src/scss/components/_calendar.scss
> +    height: 134vh;
Esto abarca MUCHÍSIMO espacio de la pantalla.

2019-10-02 17:03 UTC, YethPenado commented on src/scss/components/_calendar.scss
> +}
El archivo es bastante grande. Lo mejor sería seccionarlo más, en componentes más pequeños.

2019-10-02 17:03 UTC, YethPenado commented on src/scss/components/_calendar.scss
> +}
El archivo es bastante grande. Lo mejor sería seccionarlo más, en componentes más pequeños.

2019-10-03 03:51 UTC, jleiva requested changes

2019-10-03 03:51 UTC, jleiva commented on src/index.html
> +        <h2 class="agenda-firsthero__title hero__title--position first__title--styles">Próximas</h2>
porque separas el titulo en dos? Proximas Actividades es un solo titulo

2019-10-03 03:51 UTC, jleiva commented on src/index.html
> +            <a href="#" class="activity__info agenda__buttons--styles">Más información</a>
tenes dos clases, pero el modificador no tiene una clase base a la cual modificar, y porque necesitas un modificador?

2019-10-03 03:51 UTC, jleiva commented on src/index.html
> +            <div class="event__date">
porque event__ si todo viene usando agenda__

2019-10-03 03:51 UTC, jleiva commented on src/index.html
> +        <a href="#" class="more__activities more__activities--mgtop agenda__buttons--styles">Más actividades</a>
no es buena practica tener mas de un modificador

2019-10-03 03:51 UTC, jleiva commented on src/index.html
> +    <div class="main__title">
porque esta repetido la agenda?

2019-10-03 03:51 UTC, jleiva commented on src/scss/_base.scss
> +}
ya normalize esta en el branch develop, tenes que poner al dia tu branch

2019-10-03 03:51 UTC, jleiva commented on src/scss/components/_calendar.scss
> +  opacity: 1.1;
los valores validos para opacity van de 0 a 1, 1.1 no es valido

2019-10-03 03:51 UTC, jleiva commented on src/scss/components/_calendar.scss
> +  @media (min-width: $breakpoint-lg) {
porque ocultas la agenda?

2019-10-03 03:51 UTC, jleiva commented on src/scss/components/_calendar.scss
> +.agenda {
hero image no deberia de ser parte del partial de la agenda, ademas, porfa verifica que tus cambios de CSS cumplan con los estandares

2019-10-03 16:43 UTC, danielaaj12 commented on src/scss/_base.scss
> +p,span {
el font-titles lo estoy usando para un h3, en el diseño no aplica para que sea el font default ya que es palanquin dark y según está especificado, el font-default es quicksand

2019-10-12 17:24 UTC, jleiva requested changes

2019-10-12 17:24 UTC, jleiva commented on src/index.html
> +        <h2 class="agenda__title">Próximas
los hijos directos de un ul solo puede ser li

2019-10-12 17:24 UTC, jleiva commented on src/index.html
> +            <a href="#" class="btn btn--agenda btn--activity">Más información</a>
los botones no deberian de ser especificos por componente, que pasa si queremos usar el mismo tipo de boton en otra seccion? con estas clases tan especificas el elemento estaria como fuera de contexto

2019-10-12 17:24 UTC, jleiva commented on src/scss/components/_actvinfo.scss
> +.agenda__month,
mejor usar una clase comun en lugar de agrupar selectores

2019-10-12 17:24 UTC, jleiva commented on src/scss/components/_actvinfo.scss
> +  background: #4A4A4A;
estos colores estan en las variables?

2019-10-12 17:24 UTC, jleiva commented on src/scss/components/_actvinfo.scss
> +  font-size: 1.43rem;
hay variables para font-sizes

2019-10-12 17:24 UTC, jleiva commented on src/scss/components/_agenda.scss
> +.agenda {
porque hay estilos de agenda en el partial de actvinfo.scss?

2019-10-12 17:24 UTC, jleiva commented on src/scss/patterns/_buttons.scss
> +  font-family:$font-default;
la fuente ya esta declarada en el selector body, no hace falta declararlo aqui tambien

2019-10-14 05:01 UTC, danielaaj12 commented on src/scss/components/_agenda.scss
> +.agenda {
es que propiamente si son de los elementos que pertenecen a la info de la actividad en sí, pero voy a cambiar el nombre de clases mejor... para que no haya confusión

2019-10-14 05:01 UTC, danielaaj12 commented on src/scss/components/_actvinfo.scss
> +  background: #4A4A4A;
no porque solo tengo pensado usarlos solo para eso en el diseño de la página, pero si están en la guía de estilos, en ese caso igual los pongo por aquello que se vayan a utilizar?

2019-10-14 15:53 UTC, YethPenado commented on src/index.html
> +          <a href="#" class="btn btn--moreinfo">Más actividades</a>
El título de este botón puede ser más descriptivo, por cuestiones de accesibilidad. Una sugerencia puede ser "Ver más actividades"

2019-10-14 15:53 UTC, YethPenado commented on src/index.html
>      <div class="hero_image">
Podés ahorrarte el <div> de "hero_image" aplicando ese código al <section> respectivamente.

2019-10-14 15:53 UTC, YethPenado commented on src/index.html
>    <section class="agenda__heroimage agenda__heroimage--opacity">
La clase "agenda__heroimage--opacity" no la estás usando en ningún archivo scss

2019-10-14 15:53 UTC, YethPenado commented on src/index.html
> +      <div class=" agenda agenda__container">
Aquí hay un espacio de más,  al inicio de la declaración de la clase

2019-10-15 02:19 UTC, jleiva requested changes

2019-10-15 02:19 UTC, jleiva commented on src/scss/components/_actvinfo.scss
> +li {
todos los li del sitio van a tener esta reglas

2019-10-17 00:15 UTC, merged