Projects
cetav-ddw/cegea pull request #7
Opened 2019-10-04 19:26 UTC by LilMonRod

projects sections

2019-10-07 16:01 UTC, danielaaj12 commented on src/scss/components/_projects.scss
> +}
el sitio es responsive no adaptive, por ende tenés que utilizar la misma imagen para desktop y mobile, hay dos diferentes

2019-10-07 16:44 UTC, YethPenado commented on src/scss/styles.scss
> +@import 'components/projects';
La sección "Proyectos" se lee primero que Footer, respetando la cascada, Proyectos debería ir antes que Footer

2019-10-07 16:44 UTC, YethPenado commented on src/scss/_base.scss
> +.wrapper {
Si no seteamos un max-width, ese contenedor va a seguir creciendo. El max-width a trabajar es de 1440px.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +  @media (min-width: $breakpoint-md) {
Un salto de línea aquí.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +    height: 30vw;
Respetar el orden alfabético.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +    box-shadow: inset 0 0 0 100vw #0004;
Estas reglas se repiten bastante, podríamos hacerlas un mixin.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +  margin: 5px;
Respetar el orden alfabético.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +    position: absolute;
Respetar el orden alfabético.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +  @media (min-width: $breakpoint-md) {
Salto de línea aquí.

2019-10-07 16:44 UTC, YethPenado commented on src/scss/components/_projects.scss
> +    font-family: $font-titles;
Respetar el orden alfabético.

2019-10-09 04:11 UTC, jleiva requested changes

2019-10-09 04:11 UTC, jleiva commented on src/scss/_base.scss
> +  @media (min-width: $breakpoint-md) {
antes de este breakpoint el width es de 100% siempre?

se puede cambiar a que sea

`
width: 90%;
max-width: 1440px;
`

y asi se elimina el segundo breakpoint

es mejor mover el valor de 1440px a una variable, asi queda documentado que ese es el max-width del sitio

2019-10-09 04:11 UTC, jleiva commented on src/scss/_variables.scss
> +$dark-grey: #666666;
se puede simplificar a #666;

Otra cosa, la idea *no* es incluir en las variables todos y cada uno de los colores que usen, en las variables deberian de estar los relacionados con la guia de estilos, si por cualquier razon necesitan un color que no esta en la guia de estilos, no hace falta que sea una variable

2019-10-09 04:11 UTC, jleiva commented on src/scss/util/_mixins.scss
> +@mixin  project {
estos mixins no aportan valor, fuera de ahorrar escribir lineas, cuando se compile Sass vamos a tener los mismos bloques en los lugares donde se incluyo el mixin.

2019-10-09 04:11 UTC, jleiva commented on src/scss/components/_projects.scss
> +  & > span {
porque no ponerle una clase al span? este tipo de selectores son utiles cuando uno no tiene acceso o control del markup, pero no es el caso

2019-10-09 04:11 UTC, jleiva commented on src/index.html
> +        <div class="project projects__item--conservation">
porque los anchors de proyectos estan vacios? 

Por otro lado, lo ideal seria usar responsive images, no background image; si usan CSS para la imagen, en desktop vas a cargar las dos imagenes, ademas de que no podemos hacer lazy load

2019-10-09 04:11 UTC, jleiva commented on src/scss/_base.scss
> +.wrapper {
talvez este bloque deberia de estar dentro de un partial que se llame layout, o similar. Ahi se pueden incluir todas las reglas que se usen para armar el layout del sitio

2019-10-09 04:11 UTC, jleiva commented on src/scss/components/_projects.scss
> +  &:first-child {
esto va despues del media query

2019-10-09 04:11 UTC, jleiva commented on src/scss/components/_projects.scss
> +}
no realmente, deberiamos de usar imagenes optimizadas para las diferentes medidas del sitio

2019-10-09 23:35 UTC, LilMonRod commented on src/scss/components/_projects.scss
> +}
Pero realmente son dos imágenes diferentes, no son imágenes optimizadas porque la de mobile es una imagen redonda .png y en desktop son imágenes grandes amplias.
 y lo que se refiere Daniela es que eran dos imagenes diferentes pero porque no tenia la versión mobile de la de los jardines y se dejó temporalmente la que se tenia en el diseño pero ya se subió

2019-10-09 23:37 UTC, LilMonRod commented on src/scss/_variables.scss
> +$dark-grey: #666666;
si es un color de la guía de estilos. por eso está en variable

2019-10-09 23:39 UTC, LilMonRod commented on src/scss/util/_mixins.scss
> +@mixin  project {
recomienda que los quite? porque es correcto, se pusieron para evitar tener lineas repetidas,

2019-10-10 15:39 UTC, jleiva commented on src/index.html
> +        <div class="project projects__item--conservation">
@LilMonRod ??

2019-10-10 15:40 UTC, jleiva commented on src/scss/util/_mixins.scss
> +@mixin  project {
es lo mismo Lilliam, una vez que se compile a CSS vas a tener todo esto repetido

2019-10-10 18:00 UTC, LilMonRod commented on src/index.html
> +        <div class="project projects__item--conservation">
porque dirigen a otras secciones que todavía no están hechas. y entonces cambio esos div por img con srcset?

2019-10-12 17:29 UTC, jleiva requested changes

2019-10-12 17:29 UTC, jleiva commented on src/index.html
> +        <div class="project projects__item--conservation">
si

2019-10-12 17:29 UTC, jleiva commented on src/scss/components/_projects.scss
> +}
diay entonces si son optimizadas, son especificadas para mobile o desktop. Igual, si usamos esta manera de cargar las imagenes con CSS vamos a descargar las dos en desktop

2019-10-12 17:29 UTC, jleiva commented on src/scss/components/_projects.scss
> +  & > span {
@LilMonRod y el cambio?

2019-10-17 15:58 UTC, merged