Sección insignias lista
cetav-ddw/cegea pull request #8
Opened 2019-10-05 18:45 UTC by YethPenado

Holi චᆽච Esta es la sección de Insignias

2019-10-07 15:13 UTC, LilMonRod requested changes

2019-10-07 15:13 UTC, LilMonRod commented on src/scss/_base.scss
> +}
creo que esto lo podríamos poner de una vez en la clase wrapper seteandole los márgenes y centrándolo 
.wrapper {
  margin: 30px auto;
 @media (min-width: $breakpoint-md) {
    margin-top: 60px;
    margin-bottom: 60px;
  }
}

2019-10-07 15:13 UTC, LilMonRod commented on src/scss/components/_insignias.scss
> +    @media (min-width: $breakpoint-sm) {
salto de linea

2019-10-07 16:02 UTC, danielaaj12 commented on src/index.html
> +      <span>insignias</span>
"Insignias" va con la primer letra en mayúscula, de acuerdo al diseño = Nuestras Insignias

2019-10-07 17:20 UTC, YethPenado commented on src/index.html
> +      <span>insignias</span>
La palabra "insignias" no es un sustantivo propio y en las correcciones que ellos enviaron está en minúscula, así que no.

2019-10-09 04:15 UTC, jleiva requested changes

2019-10-09 04:15 UTC, jleiva commented on src/scss/components/_insignias.scss
> +  & > span {
lo ideal seria usar una clase, tienen todo el control sobre el markup para hacerlo

2019-10-09 04:15 UTC, jleiva commented on src/scss/_base.scss
> +.wrapper {
le puse el mismo comentario a Lilliam, esto puede vivir en un partial que se llame layout, donde esten las reglas relacionadas con estructura del sitio

2019-10-10 17:56 UTC, LilMonRod commented on src/scss/util/_layout.scss
> +    max-width: 1440px;
este segundo max-width no es necesario

2019-10-12 17:31 UTC, jleiva requested changes

2019-10-12 17:31 UTC, jleiva commented on src/scss/util/_layout.scss
> +  @media (min-width: $breakpoint-lg) {
los valores de margin son los mismo que lineas 6 y 7

2019-10-12 20:43 UTC, merged